version: '3'
services:
  webapi:
    image: sentimentfs.webapi
    build:
        context: ./src/WebApi
        dockerfile: Dockerfile
    ports:
         - "5000:80"
         - "5001:5001"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - sentimentfs

networks:
    sentimentfs:
        driver: bridge
